//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementt
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryStructure
    {
        public int EmployeeSalaryID { get; set; }
        public int EmployeeID { get; set; }
        public decimal BasicSalary { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> TA { get; set; }
        public Nullable<decimal> OtherAllowances { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public decimal NetSalary { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
